### ISSUE TITLE
Add setMin, setMax methods to Widget objects (set property feature)

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#396]
Latest Blynk app supports changing min/max properties for all widget via `setProperty` functionality. Would be nice to have `setMin(float),` `setMax(float)` methods along with `setLabel()`, `setColor()`.

Doc - http://docs.blynk.cc/#blynk-main-operations-change-widget-properties

**Comment by cffiebigc** [comment]
Hi, first of all I must say I love Blynk and thank you for making it possible. 

I would like to contribute to this library but since I'm pretty much new a the source code I would like to take a small issue like this one to start with. Do you think I can take this one an create a PR to add the described methods? If so please let me know I'll be more than happy to contribute.

**Comment by doom369** [comment]
@cffiebigc sure. Just do it :).

**Comment by cffiebigc** [comment]
Excellent! @doom369 :clap:  Do you have more documentation about contributing? like how to run the tests and everything

**Comment by doom369** [comment]
Nothing special. Just follow common coding style and that's it.
