### ISSUE TITLE
Increased number of requests re mraa on off module

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#407]
More and more support requests for the issue:

`No direct pin operations available.
Maybe you need to install mraa or onoff modules?`

**Comment by vshymanskyy** [comment]
Please provide links to such requests. Is it really a bug - who validated that?

**Comment by blynkkk** [comment]
I validated that as I'm replying to emails, intercom and drift

**Comment by vshymanskyy** [comment]
Please provide steps to reproduce, which os and Node.js version was used, sketch and other details

**Comment by vshymanskyy** [comment]
No details provided

**Comment by hsors** [comment]
I do believe there is an issue with onoff / nodejs not communicating properly with Blynk. 
I started from a fresh Debian Stretch on a Raspi 3 and installed everything according to the help page (automatic nodejs install) with 2 exceptions: 1) changed file name in the curl command to reflect my hardware (arm7l) and 2) added --unsafe-perm at the end of the "npm install onoff" line which otherwise wouldn't install).  
onoff is actually installed (when I launch node and type require("onoff"), I get "{ Gpio: { [Function: Gpio] HIGH: 1, LOW: 0 } }") but blynk client returns the famous "No direct pin operations available. Maybe you need to install mraa or onoff modules?" when I launch it and I press a widget supposed to turn a LED ON.
