### ISSUE TITLE
Create a set of good examples for Time Input Widget

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-library#414]
1. Turn on/off relay at a given time
2. Turn on/off relay at a given day and time
3. Turn on/off relay at sunrise/sunset

**Comment by ppani002** [comment]
Hello. I'm pretty new to github but I'm looking to make a contribution to a project. Excuse this random comment here when you're asking for help, but that's why I'm also here. I'd like to help with this bit as it looks like a good starting point (completely new beginner here to contributions). So you're looking for help on making examples for a widget? Where can I find the code for this Time Input Widget?

**Comment by vshymanskyy** [comment]
@ppani002 thanks for your initiative!

There are some examples for TimeInput widget already here: 
https://github.com/blynkkk/blynk-library/tree/master/examples/Widgets/TimeInput

This widget has some tricky logic, which is essentially implemented here:
https://github.com/blynkkk/blynk-library/blob/master/src/WidgetTimeInput.h

We'd need several real-life examples, that are requested via this ticket. Thx!
