### ISSUE TITLE
Template_ESP8266. Can't compile the code

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#432]
Blynk library version: [17ea7d]
IDE: [Arduino]
IDE version: [1.8.0]
Board type: [ESP8266]

### Scenario, steps to reproduce
1. Open Template_ESP8266.ino
2.  Start compilation

### Actual Result
```
In file included from sketch\BlynkProvisioning.h:16:0,

                 from C:\Users\T\AppData\Local\Temp\arduino_modified_sketch_338645\Template_ESP8266.ino:22:

C:\Users\T\Documents\Arduino\libraries\blynk-library\src/BlynkSimpleEsp8266.h:18:21: fatal error: version.h: No such file or directory

 #include <version.h>

                     ^

compilation terminated.

```

**Comment by vshymanskyy** [comment]
Arduino Core version?

**Comment by vshymanskyy** [comment]
@Refenz you should use the latest Arduino Core. Just verified, everything build perfectly.
Also, we have automatic build tests: https://travis-ci.org/blynkkk/blynk-library/builds

**Comment by wakandan** [comment]
@vshymanskyy I'm having the exact same problem. How do I check for latest Arduino Core?

**Comment by wakandan** [comment]
After update the board of esp8266 in the board manager, I can confirm that this error has gone. Thanks for the pointer.

**Comment by PaulHoets** [comment]
Hi there. I still have this issue. I have latest esp8266 boards, I have installed, reinstalled and rereinstalled the blynk parts into the arduino sketch directory, and this issue is still plaguing me. 
Help.

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266.h:18:21: fatal error: version.h: No such file or directory
 #include <version.h>
                     ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by vshymanskyy** [comment]
you should use the latest Arduino Core.
