### ISSUE TITLE
Installing Arduino library (again) with Arduino IDE

### ISSUE THREAD

**Issue by marfran94F** [blynkkk/blynk-library#94]
Same comment / issue:
Specified zip folder "does not contain valid library" (either with release v0.3.3 as with v0.3.1 before) ....

**Comment by pieman64** [comment]
I assume you are trying to add a zip library in the IDE. It isn't done this way for Blynk, maybe because there are 4 or 5 libraries used for all the functionality of Blynk (RTC etc). In the release at https://github.com/blynkkk/blynk-library/releases it clearly states you need to manually copy the libraries.

**Comment by vshymanskyy** [comment]
Yes, @pieman64 is correct. This is not an issue of Blynk, but rather Arduino IDE.
